import jsPDF from "jspdf";
import "jspdf-autotable";

let BUSINESS = {
  name: "SHMAKE",
  legalName: "Sam — Sole Trader",
  address: "Greymouth, West Coast, New Zealand",
  phone: "027 555 0000",
  email: "sam@shmake.nz",
  web: "shmake.nz",
  gstNumber: "123-456-789",
  irdNumber: "12-345-678",
  bankAccount: "03-1234-0567890-00",
  bankName: "ASB Bank",
};

export function setBusiness(config) {
  BUSINESS = { ...BUSINESS, ...config };
}

const fmt = (n) =>
  new Intl.NumberFormat("en-NZ", { style: "currency", currency: "NZD" }).format(n);

const fmtDate = (dateStr) => {
  if (!dateStr) return "";
  const d = new Date(dateStr + "T00:00:00");
  return d.toLocaleDateString("en-NZ", { day: "numeric", month: "long", year: "numeric" });
};

const COL = {
  text: "#1c1917",
  muted: "#78716c",
  amber: "#f59e0b",
  tableHead: "#f5f5f4",
  tableBorder: "#e7e5e4",
  paid: "#059669",
  overdue: "#dc2626",
  grey: "#a8a29e",
};

function drawLogo(doc, x, y) {
  doc.setFillColor(COL.amber);
  doc.roundedRect(x, y, 12, 12, 2, 2, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor("#1c1917");
  doc.text("S", x + 6, y + 8.2, { align: "center" });
}

function drawFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pw = doc.internal.pageSize.getWidth();
    const ph = doc.internal.pageSize.getHeight();
    doc.setDrawColor(COL.tableBorder);
    doc.line(20, ph - 18, pw - 20, ph - 18);
    doc.setFontSize(8);
    doc.setTextColor(COL.muted);
    doc.setFont("helvetica", "normal");
    doc.text(`Page ${i}`, pw / 2, ph - 12, { align: "center" });
    doc.text("Generated by SHMAKE", pw - 20, ph - 12, { align: "right" });
  }
}

function drawWatermark(doc, text, color) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pw = doc.internal.pageSize.getWidth();
    const ph = doc.internal.pageSize.getHeight();
    doc.saveGraphicsState();
    doc.setGState(new doc.GState({ opacity: 0.08 }));
    doc.setFontSize(60);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(color);
    const cx = pw / 2;
    const cy = ph / 2;
    doc.text(text, cx, cy, { align: "center", angle: -30 });
    doc.restoreGraphicsState();
  }
}

// ─── Invoice PDF ──────────────────────────────────────────────────────
export function generateInvoicePdf(invoice) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pw = doc.internal.pageSize.getWidth();
  let y = 20;

  // Logo + header
  drawLogo(doc, 20, y);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COL.text);
  doc.text("TAX INVOICE", pw - 20, y + 8, { align: "right" });

  y += 16;
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COL.text);
  doc.text(BUSINESS.name, 20, y);
  y += 5;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COL.muted);
  doc.text(BUSINESS.legalName, 20, y);
  y += 4;
  doc.text(BUSINESS.address, 20, y);
  y += 4;
  doc.text(`${BUSINESS.email}  |  ${BUSINESS.phone}`, 20, y);
  y += 4;
  doc.text(`GST: ${BUSINESS.gstNumber}`, 20, y);

  y += 10;

  // Bill-to + invoice details side by side
  const colL = 20;
  const colR = pw / 2 + 10;
  const boxTop = y;

  // Bill to
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COL.muted);
  doc.text("BILL TO", colL, y);
  y += 5;
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COL.text);
  doc.text(invoice.client.name, colL, y);
  y += 4.5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(COL.muted);
  if (invoice.client.address) { doc.text(invoice.client.address, colL, y); y += 4; }
  if (invoice.client.email) { doc.text(invoice.client.email, colL, y); y += 4; }
  if (invoice.client.phone) { doc.text(invoice.client.phone, colL, y); y += 4; }

  // Invoice details (right column)
  let ry = boxTop;
  const details = [
    ["Invoice:", invoice.id],
    ["Date:", fmtDate(invoice.date)],
  ];
  if (invoice.dueDate) details.push(["Due:", fmtDate(invoice.dueDate)]);
  if (invoice.linkedQuote) details.push(["Ref:", invoice.linkedQuote]);
  details.push(["Status:", invoice.status.toUpperCase()]);

  details.forEach(([label, val]) => {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(COL.muted);
    doc.text(label, colR, ry);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COL.text);
    doc.text(val, colR + 22, ry);
    ry += 5;
  });

  y = Math.max(y, ry) + 8;

  // Line items table
  doc.autoTable({
    startY: y,
    margin: { left: 20, right: 20 },
    head: [["Description", "Type", "Qty", "Rate", "Total"]],
    body: invoice.lineItems.map((li) => [
      li.description,
      li.type,
      li.quantity.toString(),
      fmt(li.unitPrice),
      fmt(li.total),
    ]),
    styles: {
      fontSize: 9,
      textColor: COL.text,
      lineColor: COL.tableBorder,
      lineWidth: 0.3,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: COL.tableHead,
      textColor: COL.text,
      fontStyle: "bold",
      lineColor: COL.tableBorder,
    },
    columnStyles: {
      0: { cellWidth: "auto" },
      1: { cellWidth: 25, halign: "center" },
      2: { cellWidth: 18, halign: "center" },
      3: { cellWidth: 28, halign: "right" },
      4: { cellWidth: 30, halign: "right" },
    },
    theme: "grid",
  });

  y = doc.lastAutoTable.finalY + 8;

  // Totals
  const totX = pw - 20;
  const lblX = totX - 55;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COL.muted);
  doc.text("Subtotal:", lblX, y, { align: "right" });
  doc.setTextColor(COL.text);
  doc.text(fmt(invoice.subtotal), totX, y, { align: "right" });
  y += 5;
  doc.setTextColor(COL.muted);
  doc.text("GST (15%):", lblX, y, { align: "right" });
  doc.setTextColor(COL.text);
  doc.text(fmt(invoice.gst), totX, y, { align: "right" });
  y += 2;
  doc.setDrawColor(COL.tableBorder);
  doc.line(lblX - 5, y, totX, y);
  y += 5;
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COL.text);
  doc.text("TOTAL:", lblX, y, { align: "right" });
  doc.text(fmt(invoice.total), totX, y, { align: "right" });

  if (invoice.status === "Paid" && invoice.paymentDate) {
    y += 5;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COL.paid);
    doc.text(`Paid on ${fmtDate(invoice.paymentDate)}`, totX, y, { align: "right" });
  }

  y += 12;

  // Payment details box (non-draft)
  if (invoice.status !== "Draft") {
    const boxH = 28;
    if (y + boxH > 260) { doc.addPage(); y = 20; }
    doc.setFillColor("#f8fafc");
    doc.setDrawColor(COL.tableBorder);
    doc.roundedRect(20, y, pw - 40, boxH, 2, 2, "FD");
    y += 6;
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(COL.muted);
    doc.text("PAYMENT DETAILS", 25, y);
    y += 5;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COL.text);
    doc.text(`Bank: ${BUSINESS.bankName}`, 25, y);
    y += 4.5;
    doc.text(`Account: ${BUSINESS.bankAccount}`, 25, y);
    y += 4.5;
    doc.text(`Reference: ${invoice.id}`, 25, y);
    if (invoice.dueDate) {
      doc.text(`Due: ${fmtDate(invoice.dueDate)}`, pw / 2, y);
    }
    y += 10;
  }

  // External note
  if (invoice.externalNote) {
    y += 2;
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(COL.muted);
    doc.text("Note:", 20, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COL.text);
    doc.text(invoice.externalNote, 35, y);
    y += 8;
  }

  // Terms
  y += 2;
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COL.muted);
  doc.text("Thank you for your business. Payment by bank transfer to the account shown above.", 20, y);

  // Watermarks
  if (invoice.status === "Paid") drawWatermark(doc, "PAID", COL.paid);
  else if (invoice.status === "Overdue") drawWatermark(doc, "OVERDUE", COL.overdue);
  else if (invoice.status === "Draft") drawWatermark(doc, "DRAFT", COL.grey);

  drawFooter(doc);
  doc.save(`${invoice.id}.pdf`);
}

// ─── Quote PDF ────────────────────────────────────────────────────────
export function generateQuotePdf(quote) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pw = doc.internal.pageSize.getWidth();
  let y = 20;

  // Logo + header
  drawLogo(doc, 20, y);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COL.text);
  doc.text("QUOTATION", pw - 20, y + 8, { align: "right" });

  y += 16;
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COL.text);
  doc.text(BUSINESS.name, 20, y);
  y += 5;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COL.muted);
  doc.text(BUSINESS.legalName, 20, y);
  y += 4;
  doc.text(BUSINESS.address, 20, y);
  y += 4;
  doc.text(`${BUSINESS.email}  |  ${BUSINESS.phone}`, 20, y);
  y += 4;
  doc.text(`GST: ${BUSINESS.gstNumber}`, 20, y);

  y += 10;

  // Client + quote details
  const colL = 20;
  const colR = pw / 2 + 10;
  const boxTop = y;

  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COL.muted);
  doc.text("PREPARED FOR", colL, y);
  y += 5;
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COL.text);
  doc.text(quote.client.name, colL, y);
  y += 4.5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(COL.muted);
  if (quote.client.address) { doc.text(quote.client.address, colL, y); y += 4; }
  if (quote.client.email) { doc.text(quote.client.email, colL, y); y += 4; }
  if (quote.client.phone) { doc.text(quote.client.phone, colL, y); y += 4; }

  // Quote details (right column)
  let ry = boxTop;
  const versionLabel = quote.version > 1 ? ` (v${quote.version})` : "";
  const details = [
    ["Quote:", `${quote.id}${versionLabel}`],
    ["Date:", fmtDate(quote.date)],
  ];
  if (quote.expiryDate) {
    details.push(["Valid until:", fmtDate(quote.expiryDate)]);
  } else {
    details.push(["Valid:", "30 days from issue"]);
  }
  if (quote.jobTitle) details.push(["Job:", quote.jobTitle]);
  details.push(["Status:", quote.status.toUpperCase()]);

  details.forEach(([label, val]) => {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(COL.muted);
    doc.text(label, colR, ry);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COL.text);
    const labelW = doc.getTextWidth(label) + 3;
    doc.text(val, colR + labelW, ry);
    ry += 5;
  });

  y = Math.max(y, ry) + 8;

  // Line items table
  doc.autoTable({
    startY: y,
    margin: { left: 20, right: 20 },
    head: [["Description", "Type", "Qty", "Rate", "Total"]],
    body: quote.lineItems.map((li) => [
      li.description,
      li.type,
      li.quantity.toString(),
      fmt(li.unitPrice),
      fmt(li.total),
    ]),
    styles: {
      fontSize: 9,
      textColor: COL.text,
      lineColor: COL.tableBorder,
      lineWidth: 0.3,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: COL.tableHead,
      textColor: COL.text,
      fontStyle: "bold",
      lineColor: COL.tableBorder,
    },
    columnStyles: {
      0: { cellWidth: "auto" },
      1: { cellWidth: 25, halign: "center" },
      2: { cellWidth: 18, halign: "center" },
      3: { cellWidth: 28, halign: "right" },
      4: { cellWidth: 30, halign: "right" },
    },
    theme: "grid",
  });

  y = doc.lastAutoTable.finalY + 8;

  // Totals
  const totX = pw - 20;
  const lblX = totX - 55;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COL.muted);
  doc.text("Subtotal:", lblX, y, { align: "right" });
  doc.setTextColor(COL.text);
  doc.text(fmt(quote.subtotal), totX, y, { align: "right" });
  y += 5;
  doc.setTextColor(COL.muted);
  doc.text("GST (15%):", lblX, y, { align: "right" });
  doc.setTextColor(COL.text);
  doc.text(fmt(quote.gst), totX, y, { align: "right" });
  y += 2;
  doc.setDrawColor(COL.tableBorder);
  doc.line(lblX - 5, y, totX, y);
  y += 5;
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COL.text);
  doc.text("TOTAL:", lblX, y, { align: "right" });
  doc.text(fmt(quote.total), totX, y, { align: "right" });

  y += 10;

  // External note
  if (quote.externalNote) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(COL.muted);
    doc.text("Note:", 20, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COL.text);
    doc.text(quote.externalNote, 35, y);
    y += 8;
  }

  // Acceptance section (only for Sent/Draft)
  if (quote.status === "Sent" || quote.status === "Draft") {
    y += 4;
    if (y + 40 > 260) { doc.addPage(); y = 20; }
    const boxH = 36;
    doc.setDrawColor(COL.tableBorder);
    doc.roundedRect(20, y, pw - 40, boxH, 2, 2, "S");
    y += 7;
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(COL.muted);
    doc.text("ACCEPTANCE", 25, y);
    y += 6;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COL.text);
    doc.text("I accept this quotation and authorise the work described above to proceed.", 25, y);
    y += 10;
    doc.text("Signed: ____________________", 25, y);
    doc.text("Date: ____________", pw / 2, y);
    y += 7;
    doc.text("Name:   ____________________", 25, y);
  }

  // Watermarks
  if (quote.status === "Accepted") drawWatermark(doc, "ACCEPTED", COL.paid);
  else if (quote.status === "Declined") drawWatermark(doc, "DECLINED", COL.overdue);
  else if (quote.status === "Expired") drawWatermark(doc, "EXPIRED", COL.grey);
  else if (quote.status === "Draft") drawWatermark(doc, "DRAFT", COL.grey);

  drawFooter(doc);
  const filename = `${quote.id}_v${quote.version}.pdf`;
  doc.save(filename);
}

// ─── Expense Report PDF ──────────────────────────────────────────────
export function generateExpenseReportPdf(expenses, dateRange, summary) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pw = doc.internal.pageSize.getWidth();
  let y = 20;

  // Logo + header
  drawLogo(doc, 20, y);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COL.text);
  doc.text("EXPENSE REPORT", pw - 20, y + 8, { align: "right" });

  y += 16;
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COL.text);
  doc.text(`${BUSINESS.name} — ${BUSINESS.legalName}`, 20, y);
  y += 5;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COL.muted);
  doc.text(`Period: ${dateRange.label}`, 20, y);
  y += 4;
  doc.text(`GST: ${BUSINESS.gstNumber}`, 20, y);

  y += 10;

  // Summary box
  doc.setFillColor("#f8fafc");
  doc.setDrawColor(COL.tableBorder);
  const sumBoxH = 10 + summary.byCategory.length * 5 + 4;
  doc.roundedRect(20, y, pw - 40, sumBoxH, 2, 2, "FD");

  y += 6;
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COL.text);
  doc.text("Total Expenses (business use):", 25, y);
  doc.text(fmt(summary.totalAmount), pw / 2, y);
  y += 5;
  doc.text("Total GST claimable:", 25, y);
  doc.text(fmt(summary.totalGst), pw / 2, y);
  y += 6;

  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COL.muted);
  doc.text("By Category:", 25, y);
  y += 4;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COL.text);
  doc.setFontSize(9);
  summary.byCategory.forEach((cat) => {
    doc.text(cat.category, 30, y);
    doc.text(fmt(cat.amount), pw / 2, y);
    y += 5;
  });

  y += 6;

  // Expenses sorted by date descending
  const sorted = [...expenses].sort((a, b) => (a.date > b.date ? -1 : 1));

  doc.autoTable({
    startY: y,
    margin: { left: 20, right: 20 },
    head: [["Date", "Description", "Cat", "Job", "Amount", "GST", "Rcpt"]],
    body: sorted.map((e) => [
      fmtDate(e.date),
      e.description + (e.apportioned ? " *" : ""),
      e.category,
      e.job || "—",
      fmt(e.amount),
      e.gst ? fmt(e.gst) : "—",
      e.hasReceipt ? "\u2713" : "\u2717",
    ]),
    foot: [["", "", "", "Totals:", fmt(summary.totalAmount), fmt(summary.totalGst), ""]],
    styles: {
      fontSize: 8,
      textColor: COL.text,
      lineColor: COL.tableBorder,
      lineWidth: 0.3,
      cellPadding: 2.5,
    },
    headStyles: {
      fillColor: COL.tableHead,
      textColor: COL.text,
      fontStyle: "bold",
      lineColor: COL.tableBorder,
    },
    footStyles: {
      fillColor: COL.tableHead,
      textColor: COL.text,
      fontStyle: "bold",
    },
    columnStyles: {
      0: { cellWidth: 28 },
      1: { cellWidth: "auto" },
      2: { cellWidth: 22 },
      3: { cellWidth: 28 },
      4: { cellWidth: 22, halign: "right" },
      5: { cellWidth: 18, halign: "right" },
      6: { cellWidth: 12, halign: "center" },
    },
    theme: "grid",
  });

  y = doc.lastAutoTable.finalY + 6;
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COL.muted);
  doc.text("* = Apportioned expense (business percentage applied)", 20, y);

  drawFooter(doc);
  const filename = `Expenses_${dateRange.label.replace(/\s+/g, "_")}.pdf`;
  doc.save(filename);
}
