-- ============================================================================
-- 002: Budget Items
-- ============================================================================

CREATE TABLE budget_items (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tax_year        int NOT NULL,
  category        text NOT NULL,
  type            text NOT NULL CHECK (type IN ('income', 'expense')),
  annual_amount   numeric(12,2) DEFAULT 0,
  monthly_amounts jsonb DEFAULT '{}'::jsonb,
  notes           text,
  created_at      timestamptz DEFAULT now(),
  updated_at      timestamptz DEFAULT now(),
  UNIQUE(tax_year, category, type)
);

CREATE TRIGGER budget_items_updated_at
BEFORE UPDATE ON budget_items
FOR EACH ROW EXECUTE FUNCTION update_updated_at();

ALTER TABLE budget_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY admin_all ON budget_items FOR ALL USING (auth.role() = 'authenticated');
