-- Add Stripe-specific tracking fields to subscription_sources
ALTER TABLE subscription_sources
  ADD COLUMN IF NOT EXISTS stripe_subscription_id text UNIQUE,
  ADD COLUMN IF NOT EXISTS stripe_customer_id text,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS current_period_start timestamptz,
  ADD COLUMN IF NOT EXISTS current_period_end timestamptz,
  ADD COLUMN IF NOT EXISTS gross_jan numeric(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fees_jan numeric(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS net_jan numeric(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gst_jan numeric(12,2) DEFAULT 0;

-- Add Stripe-specific fields to stripe_transactions
ALTER TABLE stripe_transactions
  ADD COLUMN IF NOT EXISTS stripe_customer_id text,
  ADD COLUMN IF NOT EXISTS status text;

-- Create webhook events tracking table (for idempotency)
CREATE TABLE IF NOT EXISTS stripe_webhook_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id text UNIQUE NOT NULL,
  event_type text NOT NULL,
  processed_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE stripe_webhook_events ENABLE ROW LEVEL SECURITY;

-- Admin can read webhook events for debugging
CREATE POLICY admin_read_webhook_events ON stripe_webhook_events
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_subscription_sources_stripe_subscription_id
  ON subscription_sources(stripe_subscription_id);

CREATE INDEX IF NOT EXISTS idx_subscription_sources_stripe_customer_id
  ON subscription_sources(stripe_customer_id);

CREATE INDEX IF NOT EXISTS idx_stripe_transactions_customer_id
  ON stripe_transactions(stripe_customer_id);

CREATE INDEX IF NOT EXISTS idx_webhook_events_event_id
  ON stripe_webhook_events(event_id);

-- Update existing db.js listSubscriptionSources to include new fields
COMMENT ON COLUMN subscription_sources.stripe_subscription_id IS 'Stripe subscription ID for webhook updates';
COMMENT ON COLUMN subscription_sources.status IS 'active, canceled, past_due, etc.';
