-- Manual payments for non-Stripe subscription sources
CREATE TABLE IF NOT EXISTS manual_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id bigint NOT NULL REFERENCES subscription_sources(id) ON DELETE CASCADE,
  date date NOT NULL DEFAULT CURRENT_DATE,
  gross numeric(12,2) NOT NULL DEFAULT 0,
  fee numeric(12,2) NOT NULL DEFAULT 0,
  net numeric(12,2) GENERATED ALWAYS AS (gross - fee) STORED,
  payer text,
  notes text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE manual_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY admin_all_manual_payments ON manual_payments
  FOR ALL
  USING (auth.role() = 'authenticated');

CREATE INDEX IF NOT EXISTS idx_manual_payments_source_id
  ON manual_payments(source_id);

CREATE INDEX IF NOT EXISTS idx_manual_payments_date
  ON manual_payments(date);
