-- Bank reconciliation schema updates

-- Add reconciliation columns to bank_transactions
ALTER TABLE bank_transactions
  ADD COLUMN IF NOT EXISTS bank_name text,
  ADD COLUMN IF NOT EXISTS reconciled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS import_batch uuid;

-- RLS for bank_transactions (may not exist yet)
ALTER TABLE bank_transactions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "auth_all_bank_transactions" ON bank_transactions
    FOR ALL TO authenticated USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Junction table: links one bank line to multiple invoices/expenses
CREATE TABLE IF NOT EXISTS bank_matches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bank_transaction_id bigint NOT NULL REFERENCES bank_transactions(id) ON DELETE CASCADE,
  match_type text NOT NULL CHECK (match_type IN ('invoice', 'expense')),
  invoice_id text REFERENCES invoices(id) ON DELETE SET NULL,
  expense_id bigint REFERENCES expenses(id) ON DELETE SET NULL,
  amount numeric(12,2) NOT NULL,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT chk_match_target CHECK (
    (match_type = 'invoice' AND invoice_id IS NOT NULL) OR
    (match_type = 'expense' AND expense_id IS NOT NULL)
  )
);

ALTER TABLE bank_matches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth_all_bank_matches" ON bank_matches
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT ALL ON bank_transactions TO authenticated;
GRANT ALL ON bank_matches TO authenticated;

CREATE INDEX IF NOT EXISTS idx_bank_matches_txn ON bank_matches(bank_transaction_id);
CREATE INDEX IF NOT EXISTS idx_bank_matches_inv ON bank_matches(invoice_id);
CREATE INDEX IF NOT EXISTS idx_bank_matches_exp ON bank_matches(expense_id);
CREATE INDEX IF NOT EXISTS idx_bank_txn_reconciled ON bank_transactions(reconciled);
CREATE INDEX IF NOT EXISTS idx_bank_txn_date ON bank_transactions(date DESC);
